### ISSUE TITLE
Request Status Code: 500 Error: Argument 'txt' must be a JSON string, URL or file.

### ISSUE THREAD

**Issue by vikassangwanorama** [EventStudyTools/api-wrapper.r#12]
getting error code, Request Status Code: 500
Error: Argument 'txt' must be a JSON string, URL or file.

kindly help
Vikas
Research Scholar

**Comment by adrian-ford** [comment]
I have run a few event studies this morning with no issues - doesn't look like a server issue?

**Comment by vikassangwanorama** [comment]
got the error now, The problem was due to one firm name which had a comma (,) in its name...after removing the comma...its running fine now...

**Comment by vikassangwanorama** [comment]
hi, thanks, the problem is since resolved. The problem was with my data.
In order to run Fama and French 4 factor model do I have to use the
benchmark model as "ffm4fm" in R ?
actually it is giving same results as "MM" i.e market model

**Comment by vikassangwanorama** [comment]
> I have run a few event studies this morning with no issues - doesn't look like a server issue?

HI, is fame french 4 factor model running in r..i have changed the benchmark model to "ffm4fm", but i am not getting the results
