### ISSUE TITLE
R-API performEventStudy throws error

### ISSUE THREAD

**Issue by BMasinde** [EventStudyTools/api-wrapper.r#15]
![Screenshot 2020-07-20 at 18 16 21](https://user-images.githubusercontent.com/43029260/87960826-27921d80-cab5-11ea-83c3-70c733406bed.png)
https://github.com/EventStudyTools/api-wrapper.r/blob/e845eece1e3da891dc40f2aa443cf1e37311b008/R/EventStudyAPI.R#L359

**Comment by phil240599** [comment]
I have the same problem. Did you find a solution in the meantime?

**Comment by sipemu** [comment]
Please install the current GitHub version of this package. The issue should be solved.

**Comment by phil240599** [comment]
Thank you. It works.

**Comment by BMasinde** [comment]
Thank you!
