### ISSUE TITLE
Request Status Code: 500: Argument 'txt' must be a JSON string, URL or file.

### ISSUE THREAD

**Issue by Pedernnn** [EventStudyTools/api-wrapper.r#17]
Hi 

I have just bought your package, but it does not seem to work. 
I can use the provided CSV files for the eventstudy and it gives me an output perfectly. 
However, when using my own data, which is formatted in the exact same format, R gives me the status error: 
"Request Status Code: 500 Argument 'txt' must be a JSON string, URL or file."

Is there any fix for this?
Thanks.

**Comment by sipemu** [comment]
The output will be more helpful with the current updated version.
