### ISSUE TITLE
Return in estimation window constant

### ISSUE THREAD

**Issue by moritzhtud** [EventStudyTools/api-wrapper.r#19]
Hello all, 

I am getting above error mesage for a specific event in my analysis report when performing a market model eventstudy. When I choose the same dataset but perform a 3f fama french event study I do not get any error message. Unfortunately I am not quite sure how this is possible. I am using your tool for my master thesis

Could this be a bug?
Best

**Comment by DayTrader98** [comment]
Hi moritzhtud, 

I have been using the package for a thesis as well, and I have had some other struggles. I feel that I have experience enough with trouble-shooting this (not that useful?) package. Could you perhaps share some more details,  or your data, so that we can take a look? 

Best

**Comment by moritzhtud** [comment]
Hey thanks, for the quick feedback. Please find my PrepFile attached. When uploading those values I get an error, using the market model.
[PrepFile - Upload.xlsx](https://github.com/EventStudyTools/api-wrapper.r/files/6526504/PrepFile.-.Upload.xlsx)

Please also find the error message as a screenshot
![grafik](https://user-images.githubusercontent.com/84249788/119228599-fee31600-bb13-11eb-92a1-f5c06a4a84f4.png)

I am very thankful for your help

**Comment by adrian-ford** [comment]
There seems to be a lot of rows in MarketData which will never be referenced - by the way did you run checkFiles() successfully?

**Comment by moritzhtud** [comment]
So my checkFiles does not show any error. Actually the eventstudy is performed successfully for all of my other events. Only this Event is not performed successfully. And only when I use the market model instead of the fama-french model. To the market data: my file is just a snap shot of my actual file, where I analyse more than 20 years of history. This is why I need the market data

**Comment by DayTrader98** [comment]
I have not been able to replicate the error, as I got this successful output: 
![image](https://user-images.githubusercontent.com/84605965/119230916-92214900-bb1e-11eb-8819-f31cf4da82d5.png)

I took the data you provided, and with some minor changes 
([PrepFile.-.Upload.xlsx](https://github.com/EventStudyTools/api-wrapper.r/files/6526649/PrepFile.-.Upload.xlsx)), 

...copied them into the following csv files: 
[InputFiles.zip](https://github.com/EventStudyTools/api-wrapper.r/files/6526655/InputFiles.zip)
These are the only types of csv files that worked when I had to do event studies. 

Using these three files, I got the following results:
[OutputFiles.zip](https://github.com/EventStudyTools/api-wrapper.r/files/6526656/OutputFiles.zip)

Is this useful?

**Comment by adrian-ford** [comment]
Just looking at your request file it is only 90 day estimation window finishing at 11 days before the event, this most of market data will be ignored?

**Comment by moritzhtud** [comment]
Dear DayTrader thanks! That helped alot actually.

Dear Adrian I am analysing more than 200 events which range from the year 2000 to 2020. I have one Masterfile with all the data which is processed in R. So in case of event 216 not all the market data is used. But there are many other events which will use the data.
