### ISSUE TITLE
test statistics calculation

### ISSUE THREAD

**Issue by moritzhtud** [EventStudyTools/api-wrapper.r#20]
Dear all, dear developers,
I have one question in regards to the calculated test statistics. I have checked 3 of them against the literature and it seems you calculate them totally different (maybe even wrong). Can you let us the specific part of the literature where it states you calculations are correct?

Cross sectional t test: 
I have checked it against Brown Warner (1985, p.28). The standard deviation seems to be based on the average of the AAR and not the average of the CAR like it is in your case. 

Patell z test:
It is calculated totally different and I am not sure how you do this. Is it possible to show the part of the literature. Are you totally sure of the correctness of the formulas of those tests?

Best

**Comment by sipemu** [comment]
Hello,
we evaluated the test against Eventus. Reported test statistics on our website are unified in nomenclature and may differ from original papers. 
Regards,
Simon
