### ISSUE TITLE
Request Status Code: 500 Fehler: Argument 'txt' must be a JSON string, URL or file.

### ISSUE THREAD

**Issue by amroeser** [EventStudyTools/api-wrapper.r#21]
Hello,
the following code has an error in the output.
What can I do to solve the problem?

Thank you!
```
key <- "573e58c665fcc08cc6e5a660beaad0cb"

library(EventStudy)
est <- EventStudyAPI$new()
est$authentication(apiKey = key)
```

**Comment by adrian-ford** [comment]
That looks like an old key which expired in Sep 2020 - you would need to purchase a new one.

**Comment by amroeser** [comment]
Hi,

thanks for the reply. however, the API key is advertised as free [here.](https://www.eventstudytools.com/api-key) 
Does this mean that I have to purchase an API key for the plugin so that the error disappears?
