### ISSUE TITLE
Warning: Error in : Problem with `mutate()` column `id`.

### ISSUE THREAD

**Issue by xarff** [EventStudyTools/api-wrapper.r#23]
Hello,

I bought the API key. I had issues running with my data so I tried running it with the sample data (both Dieselgate sample and SP500 example). However, it keeps on giving me error in the picture below.  

I read the previous closed issues "R-API performEventStudy throws error #15" and it was said there that current Github version should have solved the issues. Can I know which said version is this? because I installed the latest 0.35 release and this version still gives me this error.

Help me please.

![Screenshot 2021-12-14 at 10 46 07 PM](https://user-images.githubusercontent.com/96130050/146023479-6eb9ac85-eccf-4328-8450-8028bbeb4582.png)

**Comment by adrian-ford** [comment]
Hi it’s working for me on 0.36.900

**Comment by xarff** [comment]
Hello, I've only been using R for a few months now so I'm rather new to R so it's a bit confusing here and there. May I know where I can get this 0.36.900? I can't seem to find it here under the eventstudytools GitHub

> Hi it’s working for me on 0.36.900
> […](#)

**Comment by adrian-ford** [comment]
# you need to install devtools first
install.packages("devtools") 
> devtools::install_github("EventStudyTools/api-wrapper.r")

**Comment by xarff** [comment]
I found the 0.36.900 version in cran but it said there to install remotes:

install.packages("remotes")
remotes::install_github("EventStudyTools/api-wrapper.r")

Nonetheless, it finally works for me. Thanks for helping me!
