### ISSUE TITLE
Problem authenticating API

### ISSUE THREAD

**Issue by LeeHall989** [EventStudyTools/api-wrapper.r#4]
I have recently had trouble authenticating the API over the last couple of days with code I believe to be unchanged. Previously the package has been working perfectly for me. 

The code: 
apiUrl <- "http://api.eventstudytools.com"
apiKey <- "573e58c665fcc08cc6e5a660beaad0cb"
estSetup <- EventStudyAPI$new(apiUrl)
estSetup$authentication(apiKey)

Returns the error:
Request Status Code: 500
Error: Argument 'txt' must be a JSON string, URL or file.

Whether this be a bug or due to my own lack of technical expertise I am not sure at this point.
Kindest regards
Lee

**Comment by sipemu** [comment]
We had a server issue. Problem is now solved.
