### ISSUE TITLE
Warning when running the Event Study

### ISSUE THREAD

**Issue by anumanwer** [EventStudyTools/api-wrapper.r#5]
Hi,

I have uploaded the request file, the firm file and the market file but I am getting the following warning.

Please note that I am running an event study based on the values of Bitcoin. The Firm ID and Market ID are both BTC-USD.

What could be the reason for this error?

Warning: Error in : Argument 'txt' must be a JSON string, URL or file.

**Comment by oneteamx** [comment]
Hi,
I am experiencing the exact same issue as you describe in this post. Did you ever find a solution to it?

**Comment by sipemu** [comment]
The files must be formatted correctly, see https://www.eventstudytools.com/instructions-axc. I do not have it. May you provide a reproducible example?
