### ISSUE TITLE
Api key: 573e58c665fcc08cc6e5a660beaad0cb and Request Status Code: 500

### ISSUE THREAD

**Issue by marcpeine** [EventStudyTools/api-wrapper.r#6]
Request Status Code: 500
Warnung: Error in : Argument 'txt' must be a JSON string, URL or file.
  80: base::stop
  79: stop
  78: jsonlite::fromJSON
  77: retryRequest
  76: doHttrRequest
  75: estAPI$authentication
  74: observeEventHandler
   3: shiny::runApp
   2: runGadget
   1: EventStudy:::EventStudyAddin

**Comment by oneteamx** [comment]
Hi,
I am experiencing the exact same issue as you describe in this post. Did you ever find a solution to it?

**Comment by marcpeine** [comment]
no, it is a server prob

**Comment by sipemu** [comment]
Correct. Thisd is a server issue and not related to this package. I will ping the backend.

**Comment by BenJordan23** [comment]
@sipemu 
I've got the same message: "Request Status Code: 500 Fehler: Argument 'txt' must be a JSON string, URL or file." Is there a way to fix it? 

Thanks!
