### ISSUE TITLE
self$configureTask

### ISSUE THREAD

**Issue by marcpeine** [EventStudyTools/api-wrapper.r#7]
Listening on http://127.0.0.1:6246
[1] "Validate input files."
[1] "Perform Event Study"
Warnung: Error in self$configureTask: Error in configureTask: token is not set
  77: stop
  76: self$configureTask
  75: estAPI$performEventStudy
  74: observeEventHandler
   3: shiny::runApp
   2: runGadget
   1: EventStudy:::EventStudyAddin

**Comment by sipemu** [comment]
May you provide me a reproducable example?
