### ISSUE TITLE
Warning: Error in UseMethod: no applicable method for 'http_error' applied to an object of class "data.frame"

### ISSUE THREAD

**Issue by adrian-ford** [EventStudyTools/api-wrapper.r#8]
First attempts to run an event study all failed with the error below. This is using e.g. SP500 sample data. This is from the add-in (same from running in console also):

Warning: Error in UseMethod: no applicable method for 'http_error' applied to an object of class "data.frame"
  77: httr::http_error
  76: self$getTaskStatus
  75: estAPI$performEventStudy
  74: observeEventHandler
   3: shiny::runApp
   2: runGadget
   1: EventStudy:::EventStudyAddin

**Comment by sipemu** [comment]
I solved this issue today. Please install version 0.35 from github.

**Comment by adrian-ford** [comment]
> I solved this issue today. Please install version 0.35 from github.

successfully run without error thanks

**Comment by keithnicholson** [comment]
I'm seeing the same problem with 0.374-alpha.

**Comment by sipemu** [comment]
@keithnicholson Are you using our standard SP500 example?

**Comment by keithnicholson** [comment]
Yes I am.

**Comment by adrian-ford** [comment]
FYI just updated R and ran a SP500 example with 0.374-alpha - ran ok

**Comment by keithnicholson** [comment]
Which versions of R and Studio do you have?

Best regards,
Keith Nicholson
________________________________

**Comment by adrian-ford** [comment]
R 3.6.2 R Studio 1.1.463

**Comment by keithnicholson** [comment]
I have
- R 3.5.2
- R Studio 1.2.1335

I’ll upgrade R and see what happens.

Best regards,
Keith Nicholson
________________________________

**Comment by adrian-ford** [comment]
That's interesting RStudio told me I was on latest version! I just forced the upgrade to 1.2.5033 and SP500 example still tests okay for me (R still 3.6.2).

**Comment by sipemu** [comment]
It was an internal server error, not related to the R package.
